<?php

/**
 * @file
 * Contains commerce_btcpay.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\commerce_payment\Entity\PaymentGatewayInterface;

/**
 * Implements hook_entity_delete().
 */
function commerce_btcpay_entity_delete(EntityInterface $entity) {
  if ($entity instanceof PaymentGatewayInterface && $entity->getPluginId() === 'btcpay_redirect') {
    \Drupal::service('commerce_btcpay.credential_storage')->delete((string) $entity->id());
  }
}
