commerce_payment.commerce_payment_gateway.plugin.btcpay_redirect:
  type: commerce_payment_gateway_configuration
  mapping:
    server_url:
      type: string
      label: "BTCPay Server URL"
    store_id:
      type: string
      label: "Store ID"
    webhook_id:
      type: string
      label: "Webhook ID"
    send_buyer_email:
      type: boolean
      label: "Send buyer email"
    debug_mode:
      type: boolean
      label: "Debug Mode"
